### ISSUE TITLE
Include tree in the GitHub description?

### ISSUE THREAD

**Issue by wezm** [HarrisonB/ruut#4]
Today I finally had a use for `ruut` after first [becoming aware of it on Reddit](https://www.reddit.com/r/rust/comments/f84q5e/code_review_request_ruut/fijeenq) 4 months ago. However, I couldn't remember the name of the tool. I searched my GitHub stars for `tree`, without success. I ended up scanning through my Reddit comments and finding my comment on your announcement post.

Anyway, this is perhaps a silly suggestion to change the GitHub description, which currently reads, "Make easy-to-type folder and easy-to-get structures easy to read", to include the word tree to make the project a little more discoverable. Could be worth adding some topics to the repo too.

Thanks again for making `ruut`. It was handy today.

**P.S.** I also created an AUR package for it: https://aur.archlinux.org/packages/ruut/

**Comment by hibachrach** [comment]
Thank you so much for the issue! I am so glad the program was useful for you. It is now officially worth the effort, haha.

And thanks so much for creating the AUR package! I use macOS myself and I need to get around to getting it on homebrew...

**Comment by hibachrach** [comment]
Updated both the topics and description to include tree related info

🎄 hope you're having a nice day!

**Comment by wezm** [comment]
Excellent, thanks 😄
