### ISSUE TITLE
Please consider splitting out tree formatting from the command-line utility

### ISSUE THREAD

**Issue by joshtriplett** [HarrisonB/ruut#8]
I'd love to have a library crate for formatting trees in the style of `tree`. Would you consider splitting out the tree rendering from `ruut` into a library crate, without the dependencies like `structopt` and `serde_json` that would only be used for the command-line tool?

**Comment by hibachrach** [comment]
Yea if this is useful to others, I'm happy to do so.

**Comment by hibachrach** [comment]
This has finally been completed in a5902d62812b4c671ef0e368415dae09b8dddd00. See https://github.com/hibachrach/render_as_tree. Thanks for filing this!
